{
 "title": "PYRE",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ticker",
    "label": "ticker",
    "query": "SELECT ticker \nFROM (SELECT ticker, count(*) from investments GROUP BY ticker ORDER BY 2 DESC)"
   }
  ]
 },
 "panels": [
  {
   "title": "Portfolio worth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "WITH scope AS (\n  SELECT \n    sd.datetime,\n    sd.ticker,\n    (select close from stock_data tmp where tmp.datetime <= sd.datetime and tmp.ticker = sd.ticker and tmp.close is not null order by datetime desc limit 1) AS close,\n    i.price,\n    i.quantity\n  FROM stock_data sd\n  LEFT JOIN investments i\n    ON i.ticker = sd.ticker\n    AND i.datetime <= sd.datetime\n)\nSELECT\n  datetime AS time,\n  SUM(close * quantity) AS worth,\n  SUM(price * quantity) AS invested\nFROM scope\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Valuation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH scope AS (\n  SELECT \n    sd.datetime,\n    sd.ticker,\n    (select close from stock_data tmp where tmp.datetime <= sd.datetime and tmp.ticker = sd.ticker and tmp.close is not null order by datetime desc limit 1) AS close,\n    i.price,\n    i.quantity\n  FROM stock_data sd\n  LEFT JOIN investments i\n    ON i.ticker = sd.ticker\n    AND i.datetime <= sd.datetime\n)\nSELECT\n  datetime AS time,\n  SUM(close * quantity) AS worth,\n  SUM(price * quantity) AS invested\nFROM scope\nGROUP BY datetime\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Gains / Loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH scope AS (\n  SELECT \n    sd.datetime,\n    sd.ticker,\n    (select close from stock_data tmp where tmp.datetime <= sd.datetime and tmp.ticker = sd.ticker and tmp.close is not null order by datetime desc limit 1) AS close,\n    i.price,\n    i.quantity\n  FROM stock_data sd\n  LEFT JOIN investments i\n    ON i.ticker = sd.ticker\n    AND i.datetime <= sd.datetime\n)\nSELECT\n  datetime AS time,\n  SUM(close * quantity) - SUM(price * quantity) AS gains\nFROM scope\nGROUP BY datetime\nORDER BY datetime"
    }
   ]
  },
  { "title": "$ticker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "ticker" },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n datetime AS time,\n close\nFROM stock_data\nWHERE $__timeFilter(datetime)\n  AND ticker = $ticker"
    }
   ]
  },
  {
   "title": "Valuation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH\ncombined AS (\n    SELECT\n        sd.ticker,\n        sd.datetime,\n        sd.close,\n        i.quantity\n    FROM\n        stock_data sd\n    LEFT JOIN investments i\n        ON sd.ticker = i.ticker AND sd.datetime >= i.datetime\n)\nSELECT\n    ticker,\n    datetime AS time,\n    close * SUM(quantity) AS value\nFROM\n    combined\nWHERE $__timeFilter(datetime)\n  AND ticker = $ticker\nGROUP BY \n    ticker,\n    datetime,\n    close\nORDER BY\n    datetime;"
    }
   ]
  },
  {
   "title": "Gains / Loss",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH\ncombined AS (\n    SELECT\n        sd.ticker,\n        sd.datetime,\n        sd.close,\n        i.price,\n        i.quantity,\n        i.fees\n    FROM\n        stock_data sd\n    LEFT JOIN investments i\n        ON sd.ticker = i.ticker AND sd.datetime >= i.datetime\n)\nSELECT\n    ticker,\n    datetime AS time,\n    close * SUM(quantity) - SUM(price * quantity + fees)\nFROM\n    combined\nWHERE $__timeFilter(datetime)\n  AND ticker = $ticker\nGROUP BY \n    ticker,\n    datetime,\n    close\nORDER BY\n    datetime;"
    }
   ]
  },
  {
   "title": "Last session close price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT close\nFROM stock_data\nWHERE $__timeFilter(datetime) AND ticker = $ticker"
    }
   ]
  },
  {
   "title": "PRU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(price * quantity + fees) / sum(quantity)\nFROM investments\nWHERE ticker = $ticker"
    }
   ]
  }
 ]
}