apiVersion: 1

datasources:
  - name: pyre
    uid: pyre
    type: postgres
    url: $PYRE_DB_URL
    database: $PYRE_DB_NAME
    user: $PYRE_DB_USER
    basicAuth: false
    secureJsonData:
      password: $PYRE_DB_PASSWORD
    jsonData:
      sslmode: "disable"
      tlsAuth: false
      tlsAuthWithCACert: false
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
    isDefault: true
