CONTRIBUTION_SOCIALE_GENERALISEE = CSG = 0.092
CONTRIBUTION_AU_REMBOURSEMENT_DE_LA_DETTE_SOCIALE = CRDS = 0.005
PRELEVEMENT_DE_SOLIDARITE = PDS = 0.075
IMPOT_SUR_LE_REVENU = ISR = 0.128

PRELEVEMENT_SOCIAUX = PS = CSG + CRDS + PDS
PRELEVEMENT_FORFAITAIRE_UNIQUE = PFU = PS + ISR
