name: Docker build

on:
  workflow_call:
    inputs:
      image-name:
        description: "Image name"
        type: string
        required: true
      image-tag:
        description: "Image tag"
        type: string
        required: false
        default: "latest"
      push:
        description: "Wether to push to dockerhub"
        type: boolean
        required: false
        default: false

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to dockerhub
      run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Build docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/${{ inputs.image-name }}:${{ inputs.image-tag }} -t $DOCKERHUB_USERNAME/${{ inputs.image-name }}:latest .
        
    - name: Push docker image
      if: ${{ inputs.push }}
      run: |
        docker push $DOCKERHUB_USERNAME/${{ inputs.image-name }}:${{ inputs.image-tag }}
        docker push $DOCKERHUB_USERNAME/${{ inputs.image-name }}:latest

